# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pets',
        ),
    ]
