# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_first_name', models.CharField(max_length=200)),
                ('human_last_name', models.CharField(max_length=200)),
                ('pet_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.PositiveSmallIntegerField()),
                ('primary_phone', models.PositiveIntegerField()),
            ],
        ),
    ]
