# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('human_first_name', models.CharField(max_length=200)),
                ('human_last_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', localflavor.us.models.USStateField()),
                ('zip', localflavor.us.models.USZipCodeField()),
                ('primary_phone', localflavor.us.models.PhoneNumberField()),
                ('secondary_phone', localflavor.us.models.PhoneNumberField()),
                ('email', models.EmailField(max_length=254)),
                ('vet_name', models.CharField(max_length=200)),
                ('vet_phone', localflavor.us.models.PhoneNumberField()),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', localflavor.us.models.PhoneNumberField()),
                ('contract_on_file', models.BooleanField()),
                ('left_rating', models.BooleanField()),
                ('allows_pics', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestingFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
