# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('human_first_name', models.CharField(max_length=200)),
                ('human_last_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', localflavor.us.models.USStateField()),
                ('zip_code', localflavor.us.models.USZipCodeField()),
                ('primary_phone', localflavor.us.models.PhoneNumberField()),
                ('secondary_phone', localflavor.us.models.PhoneNumberField()),
                ('email', models.EmailField(max_length=254)),
                ('vet_name', models.CharField(max_length=200)),
                ('vet_phone', localflavor.us.models.PhoneNumberField()),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', localflavor.us.models.PhoneNumberField()),
                ('contract_on_file', models.BooleanField()),
                ('left_rating', models.BooleanField()),
                ('allows_pics', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Katie', max_length=200)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestingFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
