# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_app.Customers'),
        ),
        migrations.AddField(
            model_name='pets',
            name='name',
            field=models.CharField(default='Katie', max_length=200),
        ),
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
